# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-10-28 11:10-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: pinakes/common/auth/keycloak_django/authentication.py:76
msgid "Invalid authorization header. No credentials provided."
msgstr "無効な認証ヘッダーです。認証情報が提供されていません。"

#: pinakes/common/auth/keycloak_django/authentication.py:80
msgid ""
"Invalid authorization header. Credentials string should not contain spaces."
msgstr "無効な認証ヘッダーです。認証情報の文字列にスペースは使用できません。"

#: pinakes/common/auth/keycloak_django/authentication.py:107
msgid "No valid JWK found."
msgstr "有効な JWK が見つかりません。"

#: pinakes/common/auth/keycloak_django/authentication.py:119
msgid "Signature has expired."
msgstr "署名の有効期限が切れました。"

#: pinakes/common/auth/keycloak_django/authentication.py:121
msgid "Invalid claims."
msgstr "無効な要求です。"

#: pinakes/common/auth/keycloak_django/authentication.py:123
msgid "Invalid signature."
msgstr "無効な署名です。"

#: pinakes/common/auth/keycloak_django/authentication.py:163
msgid "Token expired"
msgstr "トークンの有効期限が切れました"

#: pinakes/common/auth/keycloak_django/authentication.py:168
#: pinakes/common/auth/keycloak_django/authentication.py:172
msgid "Invalid audience"
msgstr "無効なオーディエンス"

#: pinakes/common/exception_handler.py:27
msgid "Internal Error"
msgstr "内部エラー"

#: pinakes/common/exception_handler.py:31
msgid "{}. Report to the support team if it is not an user error."
msgstr "{}。これがユーザーエラーでない場合は、サポートチームに報告してください。"

#: pinakes/common/exception_handler.py:37
msgid "Unauthorized"
msgstr "許可されていません"

#: pinakes/common/image_mixin.py:43
msgid "{} object has no attribute 'icon'."
msgstr "{} オブジェクトに属性 'アイコン' が定義されていません。"

#: pinakes/common/image_mixin.py:69
msgid "Icon attribute has been set on {} object (id: {})."
msgstr "アイコン属性が {} オブジェクト (id: {}) に設定されています。"

#: pinakes/common/image_mixin.py:95 pinakes/common/image_mixin.py:123
msgid "Icon attribute has not been set on {} object (id: {})."
msgstr "アイコン属性が {} オブジェクト (id: {}) に設定されていません。"

#: pinakes/common/models/fields.py:14
msgid "An encrypted JSON object"
msgstr "暗号化された JSON オブジェクト"

#: pinakes/main/analytics/analytics_collectors.py:23
msgid "General platform configuration."
msgstr "一般的なプラットフォーム構成。"

#: pinakes/main/analytics/analytics_collectors.py:64
msgid "Data on sources"
msgstr "ソースに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:89
msgid "Data on service_offerings"
msgstr "サービスオファリングに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:119
msgid "Data on service_offering_nodes"
msgstr "サービスオファリングノードに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:150
msgid "Data on service_instances"
msgstr "サービスインスタンスに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:180
msgid "Data on service_inventories"
msgstr "サービスインベントリーに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:209
msgid "Data on portfolios"
msgstr "ポートフォリオに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:236
msgid "Data on portfolio_items"
msgstr "ポートフォリオアイテムに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:267
msgid "Data on orders"
msgstr "オーダーに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:294
msgid "Data on order_items"
msgstr "オーダーアイテムに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:328
msgid "Data on approval_requests"
msgstr "承認リクエストに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:355
msgid "Data on service_plans"
msgstr "サービスプランに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:383
msgid "Data on templates"
msgstr "テンプレートに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:407
msgid "Data on workflows"
msgstr "ワークフローに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:434
msgid "Data on requests"
msgstr "リクエストに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:469
msgid "Data on actions"
msgstr "アクションに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:495
msgid "Data on tag_links"
msgstr "タグリンクに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:522
msgid "Data on groups"
msgstr "グループに関するデータ"

#: pinakes/main/analytics/analytics_collectors.py:544
msgid "Counts of orders by products"
msgstr "製品別のオーダー数"

#: pinakes/main/analytics/analytics_collectors.py:581
msgid "Counts of tags by portfolios"
msgstr "ポートフォリオ別のタグの数"

#: pinakes/main/analytics/analytics_collectors.py:615
msgid "Counts of tags by products"
msgstr "製品別のタグの数"

#: pinakes/main/analytics/analytics_collectors.py:649
msgid "Counts of tags by service_intentories"
msgstr "サービスインベントリー別のタグの数"

#: pinakes/main/analytics/analytics_collectors.py:683
msgid "Order data by product"
msgstr "製品別のオーダーデータ"

#: pinakes/main/analytics/analytics_collectors.py:783
msgid "Approval request time spent by group"
msgstr "グループによって費やされた承認リクエストの時間"

#: pinakes/main/approval/exceptions.py:8
msgid "Insufficient query parameters"
msgstr "クエリーパラメーターが不十分です"

#: pinakes/main/approval/exceptions.py:13
msgid "Invalid State Transition"
msgstr "無効な状態遷移"

#: pinakes/main/approval/exceptions.py:18
msgid "Field cannot be blank"
msgstr "フィールドを空白にすることはできません"

#: pinakes/main/approval/exceptions.py:23
msgid "Duplicated UUID for approver groups"
msgstr "承認者グループの UUID が重複しています"

#: pinakes/main/approval/exceptions.py:28
msgid "Group has no approver role"
msgstr "グループに承認者ロールがありません"

#: pinakes/main/approval/exceptions.py:33
msgid "Group does not exist"
msgstr "グループは存在しません"

#: pinakes/main/approval/exceptions.py:38
msgid "There are resource objects linked to the workflow"
msgstr "ワークフローにリンクされているリソースオブジェクトがあります"

#: pinakes/main/approval/exceptions.py:43
msgid "Workflow is in use"
msgstr "ワークフローは使用中です"

#: pinakes/main/approval/services/create_action.py:49
msgid "The memo message cannot be blank"
msgstr "メモのメッセージを空白にすることはできません"

#: pinakes/main/approval/services/create_action.py:56
msgid "Current request is not pending state"
msgstr "現在のリクエストは保留中の状態ではありません"

#: pinakes/main/approval/services/create_action.py:64
msgid "Current request is not started state"
msgstr "現在のリクエストは開始済みの状態ではありません"

#: pinakes/main/approval/services/create_action.py:72
msgid "Current request is not in pending state"
msgstr "現在のリクエストは保留中の状態ではありません"

#: pinakes/main/approval/services/create_action.py:80
#: pinakes/main/approval/services/create_action.py:97
msgid "Current request is not in notified state"
msgstr "現在のリクエストは通知済みの状態ではありません"

#: pinakes/main/approval/services/create_action.py:85
msgid "Only child level request can be approved"
msgstr "承認できるのは子レベルのリクエストだけです"

#: pinakes/main/approval/services/create_action.py:102
msgid "Only child level request can be denied"
msgstr "拒否できるのは子レベルのリクエストだけです"

#: pinakes/main/approval/services/create_action.py:107
msgid "A reason has to be provided if a request is being denied"
msgstr "リクエストを拒否する場合は、理由を記述する必要があります"

#: pinakes/main/approval/services/create_action.py:119
msgid "Only root level request can be canceled"
msgstr "取り消しできるのはルートレベルのリクエストだけです"

#: pinakes/main/approval/services/create_action.py:124
msgid "The request has already finished"
msgstr "リクエストはすでに終了しています"

#: pinakes/main/approval/services/create_action.py:136
msgid "Current request has already finished"
msgstr "現在のリクエストはすでに終了しています"

#: pinakes/main/approval/services/create_action.py:140
msgid "Failure reason is missing"
msgstr "失敗の理由がありません"

#: pinakes/main/approval/services/create_action.py:144
msgid "Only child level request can be flagged error"
msgstr "エラーのフラグを付けられるのは子レベルのリクエストだけです"

#: pinakes/main/approval/services/email_notification.py:92
msgid "Failed to email group {}"
msgstr "グループ {} にメールを送信できませんでした"

#: pinakes/main/approval/services/update_request.py:19
msgid "Auto-approved"
msgstr "自動承認済み"

#: pinakes/main/approval/validations.py:58
msgid "Group id {} does not exist"
msgstr "グループ id {} は存在しません"

#: pinakes/main/approval/validations.py:66
msgid "Group {} does not have approver role"
msgstr "グループ {} には approver ロールがありません"

#: pinakes/main/approval/views.py:186
msgid "Insufficient resource object params: {}"
msgstr "不十分なリソースオブジェクトパラメーター: {}"

#: pinakes/main/auth/views.py:58
msgid "Logout is not supported with Bearer auth."
msgstr "ログアウト は Bearer 認証ではサポート対象外です。"

#: pinakes/main/catalog/exceptions.py:8
msgid "Bad query parameters"
msgstr "無効なクエリーパラメーター"

#: pinakes/main/catalog/exceptions.py:13
msgid "Invalid survey"
msgstr "無効な Survey"

#: pinakes/main/catalog/exceptions.py:18
msgid "Uncancelable Order"
msgstr "取り消し不可能なオーダー"

#: pinakes/main/catalog/models.py:190
msgid "Info"
msgstr "情報"

#: pinakes/main/catalog/models.py:191
msgid "Error"
msgstr "エラー"

#: pinakes/main/catalog/models.py:192
msgid "Warning"
msgstr "警告"

#: pinakes/main/catalog/models.py:193
msgid "Debug"
msgstr "デバッグ"

#: pinakes/main/catalog/models.py:332 pinakes/main/catalog/models.py:419
msgid "Approval Pending"
msgstr "承認は保留中"

#: pinakes/main/catalog/models.py:333 pinakes/main/catalog/models.py:420
msgid "Approved"
msgstr "承認済"

#: pinakes/main/catalog/models.py:334 pinakes/main/catalog/models.py:421
msgid "Canceled"
msgstr "取り消し済み"

#: pinakes/main/catalog/models.py:335 pinakes/main/catalog/models.py:422
msgid "Completed"
msgstr "完了済み"

#: pinakes/main/catalog/models.py:336 pinakes/main/catalog/models.py:423
msgid "Created"
msgstr "作成日時"

#: pinakes/main/catalog/models.py:337 pinakes/main/catalog/models.py:424
msgid "Denied"
msgstr "拒否済み"

#: pinakes/main/catalog/models.py:338 pinakes/main/catalog/models.py:425
#: pinakes/main/models.py:67
msgid "Failed"
msgstr "失敗"

#: pinakes/main/catalog/models.py:339 pinakes/main/catalog/models.py:426
msgid "Ordered"
msgstr "オーダー済み"

#: pinakes/main/catalog/models.py:549
#, python-format
msgid ""
"Created Approval Request ref: %(approval_request_ref)s. Catalog approval "
"request id: %(approval_request_id)s"
msgstr "承認リクエストのリファレンスを作成しました: %(approval_request_ref)s。カタログ承認リクエスト ID: %(approval_request_id)s"

#: pinakes/main/catalog/models.py:569
msgid "undecided"
msgstr "未決定"

#: pinakes/main/catalog/models.py:570
msgid "approved"
msgstr "承認"

#: pinakes/main/catalog/models.py:571
msgid "canceled"
msgstr "取り消し済み"

#: pinakes/main/catalog/models.py:572
msgid "denied"
msgstr "拒否"

#: pinakes/main/catalog/models.py:573
msgid "failed"
msgstr "失敗"

#: pinakes/main/catalog/serializers.py:410
msgid "Order"
msgstr "オーダー"

#: pinakes/main/catalog/serializers.py:411
msgid "OrderItem"
msgstr "オーダーアイテム"

#: pinakes/main/catalog/services/cancel_order.py:61
msgid "Order {} is not cancel able in its current state: {}"
msgstr "オーダー {} は、現在の状態では取り消すことができません: {}"

#: pinakes/main/catalog/services/collect_tag_resources.py:62
msgid "Portfolio item {} does not have related service offering"
msgstr "ポートフォリオアイテム {} には、関連するサービスオファリングがありません"

#: pinakes/main/catalog/services/copy_portfolio_item.py:47
msgid "{} is not order able, and cannot be copied"
msgstr "{} をオーダーすることはできません。またコピーすることはできません"

#: pinakes/main/catalog/services/finish_order.py:31
#, python-format
msgid "Order %(order_id)s has failed"
msgstr "オーダー %(order_id)s が失敗しました"

#: pinakes/main/catalog/services/finish_order.py:36
#, python-format
msgid "Order %(order_id)s is completed"
msgstr "オーダー %(order_id)s が完了しました"

#: pinakes/main/catalog/services/finish_order.py:44
msgid "Order Canceled"
msgstr "オーダーが取り消されました"

#: pinakes/main/catalog/services/finish_order.py:48
msgid "Order Failed"
msgstr "オーダーが失敗しました"

#: pinakes/main/catalog/services/finish_order.py:53
#, python-format
msgid ""
"This order item has failed due to the entire order %(state)s before it ran"
msgstr "このオーダーアイテムは、実行する前にオーダー全体 %(state)s が原因で失敗しました"

#: pinakes/main/catalog/services/finish_order_item.py:34
#, python-format
msgid "Order Item %(id)s is completed"
msgstr "オーダーアイテム %(id)s が完了しました"

#: pinakes/main/catalog/services/handle_approval_events.py:76
msgid "Internal Error. Please contact our support team."
msgstr "内部エラー。サポートチームにご連絡ください。"

#: pinakes/main/catalog/services/handle_approval_events.py:109
#, python-format
msgid "Approval Request finished with status %(state)s"
msgstr "承認リクエストが %(state)s のステータスで終了しました"

#: pinakes/main/catalog/services/handle_approval_events.py:115
#, python-format
msgid "Approval Request finished with status %(state)s and reason %(reason)s"
msgstr "承認リクエストが %(state)s のステータスおよび %(reason)s の理由で終了しました"

#: pinakes/main/catalog/services/provision_order_item.py:30
#, python-format
msgid "Order Item %(id)s is provisioned"
msgstr "オーダーアイテム %(id)s がプロビジョニングされました"

#: pinakes/main/catalog/services/sanitize_parameters.py:42
msgid "parameter {} is required and must have a value"
msgstr "パラメーター {} は必須で、値を設定する必要があります"

#: pinakes/main/catalog/services/start_order.py:21
msgid "Submitting Order for provisioning"
msgstr "プロビジョニングのためにオーダーを送信中"

#: pinakes/main/catalog/services/start_order_item.py:53
#, python-format
msgid "Submitting Order Item %(item_id)s for provisioning"
msgstr "プロビジョニングのためにオーダーアイテム %(item_id)s を送信中"

#: pinakes/main/catalog/services/submit_approval_request.py:61
msgid "Failed to submit request to approval for Order {}, error: {}"
msgstr "オーダー {} の承認リクエストの送信に失敗しました。エラー: {}"

#: pinakes/main/catalog/services/validate_order_item.py:45
msgid ""
"The underlying survey on product {} in the portfolio {} has been changed and "
"is no longer valid, please contact an administrator to reset it."
msgstr "ポートフォリオ {} の製品 {} のベースとなる Survey が変更され、有効ではなくなりました。管理者に連絡してリセットしてください。"

#: pinakes/main/catalog/views.py:521
msgid "Order {} does not have related order items"
msgstr "オーダー {} には関連するオーダーアイテムがありません"

#: pinakes/main/catalog/views.py:531
#, python-format
msgid "Computed tags for order %(order_id)d: %(tag_resources)s"
msgstr "オーダー %(order_id) の計算済みタグ: %(tag_resources)s"

#: pinakes/main/inventory/exceptions.py:8
msgid "Refresh already registered"
msgstr "更新はすでに登録されています"

#: pinakes/main/inventory/serializers.py:50
#, python-format
msgid "%(name)s is unavailable, refresh skipped"
msgstr "%(name)s は利用できません。更新をスキップしました"

#: pinakes/main/inventory/serializers.py:55
#, python-format
msgid "Refresh failed: %(error)s"
msgstr "更新に失敗しました: %(error)s"

#: pinakes/main/inventory/serializers.py:59
msgid "adds"
msgstr "追加"

#: pinakes/main/inventory/serializers.py:60
msgid "deletes"
msgstr "削除"

#: pinakes/main/inventory/serializers.py:61
msgid "updates"
msgstr "更新"

#: pinakes/main/inventory/serializers.py:83
#, python-format
msgid "Service Inventories: %(stats)s;\n"
msgstr "サービスインベントリー: %(stats)s;\n"

#: pinakes/main/inventory/serializers.py:88
#, python-format
msgid "Job Templates & Workflows: %(soi_stats)s;\n"
msgstr "ジョブテンプレートおよびワークフロー: %(soi_stats)s;\n"

#: pinakes/main/inventory/serializers.py:93
#, python-format
msgid "Workflow Template Nodes: %(son_stats)s;\n"
msgstr "ワークフローテンプレートノード: %(son_stats)s;\n"

#: pinakes/main/inventory/serializers.py:97
#, python-format
msgid "Service Plan: %(sp_stats)s;\n"
msgstr "サービスプラン: %(sp_stats)s;\n"

#: pinakes/main/inventory/serializers.py:102
msgid "Nothing to update"
msgstr "更新するものはありません"

#: pinakes/main/inventory/serializers.py:125
#, python-format
msgid ""
"Source cannot be changed to url %(new_url)s uuid %(new_install_uuid)s, "
"currently bound to url %(url)s with uuid %(install_uuid)s"
msgstr "ソースを URL %(new_url)s UUID %(new_install_uuid)s に変更することはできません。現在、UUID %(install_uuid)s で URL %(url)s にバインドされています"

#: pinakes/main/inventory/serializers.py:131
#, python-format
msgid "Error: %(error)s"
msgstr "エラー: %(error)s"

#: pinakes/main/inventory/services/collect_inventory_tags.py:38
msgid "ServiceOffering object {} not found"
msgstr "サービスオファリングのオブジェクト {} が見つかりません"

#: pinakes/main/inventory/services/get_service_offering.py:34
msgid "Failed to get service offering [{}]"
msgstr "サービスオファリング [{}] の取得に失敗しました"

#: pinakes/main/inventory/task_utils/check_source_availability.py:55
msgid "Check availability completed"
msgstr "アベイラビリティーの確認が完了しました"

#: pinakes/main/inventory/task_utils/launch_job.py:68
#, python-format
msgid "Job %(id)s has %(status)s status"
msgstr "ジョブ %(id)s は %(status)s のステータスです"

#: pinakes/main/inventory/views.py:89
msgid "Refresh job {} is already {}, please try again later"
msgstr "ジョブ {} の更新はすでに {} です。後でやり直してください"

#: pinakes/main/models.py:65
msgid "Done"
msgstr "完了"

#: pinakes/main/models.py:66
msgid "InProgress"
msgstr "進行中"

#: pinakes/main/models.py:68
msgid "Unknown"
msgstr "不明"

