# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-05-16 13:56+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: pinakes/common/image_mixin.py:43
msgid "{} object has no attribute 'icon'."
msgstr "{} オブジェクトに属性 'アイコン' が定義されていません。"

#: pinakes/common/image_mixin.py:69
msgid "Icon attribute has been set on {} object (id: {})."
msgstr "アイコン属性が {} オブジェクト (id: {}) に設定されています。"

#: pinakes/common/image_mixin.py:95 pinakes/common/image_mixin.py:123
msgid "Icon attribute has not been set on {} object (id: {})."
msgstr "アイコン属性が {} オブジェクト (id: {}) に設定されていません。"

#: pinakes/main/analytics/analytics_collectors.py:21
msgid "General platform configuration."
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:60
msgid "Data on sources"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:84
#, fuzzy
#| msgid "Failed to get service offering [{}]"
msgid "Data on service_offerings"
msgstr "サービスオファリング [{}] の取得に失敗しました"

#: pinakes/main/analytics/analytics_collectors.py:114
msgid "Data on service_offering_nodes"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:145
msgid "Data on service_instances"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:175
msgid "Data on service_inventories"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:204
msgid "Data on portfolios"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:231
msgid "Data on portfolio_items"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:262
msgid "Data on orders"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:289
msgid "Data on order_items"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:323
msgid "Data on approval_requests"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:350
msgid "Data on service_plans"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:378
msgid "Data on templates"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:402
msgid "Data on workflows"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:429
msgid "Data on requests"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:464
msgid "Data on actions"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:490
msgid "Data on tag_links"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:517
msgid "Data on groups"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:539
msgid "Counts of orders by products"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:576
msgid "Counts of tags by portfolios"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:610
msgid "Counts of tags by products"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:644
msgid "Counts of tags by service_intentories"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:678
msgid "Order data by product"
msgstr ""

#: pinakes/main/analytics/analytics_collectors.py:777
msgid "Approval request time spent by group"
msgstr ""

#: pinakes/main/approval/exceptions.py:8
msgid "Insufficient query parameters"
msgstr "クエリーパラメーターが不十分です"

#: pinakes/main/approval/exceptions.py:13
msgid "Invalid State Transition"
msgstr "無効な状態遷移"

#: pinakes/main/approval/exceptions.py:18
msgid "Field cannot be blank"
msgstr "フィールドを空白にすることはできません"

#: pinakes/main/approval/exceptions.py:23
msgid "Duplicated UUID for approver groups"
msgstr "承認者グループの UUID が重複しています"

#: pinakes/main/approval/exceptions.py:28
msgid "Group has no approver role"
msgstr "グループに承認者ロールがありません"

#: pinakes/main/approval/exceptions.py:33
msgid "Group does not exist"
msgstr "グループは存在しません"

#: pinakes/main/approval/services/create_action.py:49
msgid "The memo message cannot be blank"
msgstr "メモのメッセージを空白にすることはできません"

#: pinakes/main/approval/services/create_action.py:56
msgid "Current request is not pending state"
msgstr "現在のリクエストは保留中の状態ではありません"

#: pinakes/main/approval/services/create_action.py:64
msgid "Current request is not started state"
msgstr "現在のリクエストは開始済みの状態ではありません"

#: pinakes/main/approval/services/create_action.py:72
msgid "Current request is not in pending state"
msgstr "現在のリクエストは保留中の状態ではありません"

#: pinakes/main/approval/services/create_action.py:80
#: pinakes/main/approval/services/create_action.py:97
msgid "Current request is not in notified state"
msgstr "現在のリクエストは通知済みの状態ではありません"

#: pinakes/main/approval/services/create_action.py:85
msgid "Only child level request can be approved"
msgstr "承認できるのは子レベルのリクエストだけです"

#: pinakes/main/approval/services/create_action.py:102
msgid "Only child level request can be denied"
msgstr "拒否できるのは子レベルのリクエストだけです"

#: pinakes/main/approval/services/create_action.py:107
msgid "A reason has to be provided if a request is being denied"
msgstr "リクエストを拒否する場合は、理由を記述する必要があります"

#: pinakes/main/approval/services/create_action.py:119
msgid "Only root level request can be canceled"
msgstr "取り消しできるのはルートレベルのリクエストだけです"

#: pinakes/main/approval/services/create_action.py:124
msgid "The request has already finished"
msgstr "リクエストはすでに終了しています"

#: pinakes/main/approval/services/create_action.py:136
msgid "Current request has already finished"
msgstr "現在のリクエストはすでに終了しています"

#: pinakes/main/approval/services/create_action.py:140
msgid "Failure reason is missing"
msgstr "失敗の理由がありません"

#: pinakes/main/approval/services/create_action.py:144
msgid "Only child level request can be flagged error"
msgstr "エラーのフラグを付けられるのは子レベルのリクエストだけです"

#: pinakes/main/approval/services/email_notification.py:91
msgid "Failed to email group {}"
msgstr "グループ {} にメールを送信できませんでした"

#: pinakes/main/approval/services/update_request.py:19
msgid "Auto-approved"
msgstr "自動承認済み"

#: pinakes/main/approval/validations.py:56
msgid "Group id {} does not exist"
msgstr "グループ id {} は存在しません"

#: pinakes/main/approval/validations.py:64
msgid "Group {} does not have approver role"
msgstr "グループ {} には approver ロールがありません"

#: pinakes/main/approval/views.py:189
msgid "Insufficient resource object params: {}"
msgstr "不十分なリソースオブジェクトパラメーター: {}"

#: pinakes/main/catalog/exceptions.py:8
msgid "Bad query parameters"
msgstr "無効なクエリーパラメーター"

#: pinakes/main/catalog/exceptions.py:13
msgid "Invalid survey"
msgstr "無効な Survey"

#: pinakes/main/catalog/exceptions.py:18
msgid "Uncancelable Order"
msgstr ""

#: pinakes/main/catalog/models.py:537
msgid "Created Approval Request ref: {}. Catalog approval request id: {}"
msgstr ""
"承認リクエストのリファレンスを作成しました: {}。カタログ承認リクエスト ID: {}"

#: pinakes/main/catalog/services/cancel_order.py:61
msgid "Order {} is not cancel able in its current state: {}"
msgstr ""

#: pinakes/main/catalog/services/collect_tag_resources.py:62
msgid "Portfolio item {} does not have related service offering"
msgstr ""
"ポートフォリオアイテム {} には、関連するサービスオファリングがありません"

#: pinakes/main/catalog/services/copy_portfolio_item.py:47
#, fuzzy
#| msgid "{} is not orderable, and cannot be copied"
msgid "{} is not order able, and cannot be copied"
msgstr "{} をオーダーすることはできません。またコピーすることはできません"

#: pinakes/main/catalog/services/finish_order.py:32
msgid "Order {} has failed"
msgstr "Order {} が失敗しました"

#: pinakes/main/catalog/services/finish_order.py:37
msgid "Order {} is completed"
msgstr "オーダー {} が完了しました"

#: pinakes/main/catalog/services/finish_order.py:54
msgid "This order item has failed due to the entire order {} before it ran"
msgstr ""
"このオーダーアイテムは、実行する前にオーダー全体 {} が原因で失敗しました"

#: pinakes/main/catalog/services/finish_order_item.py:35
msgid "Order Item {} is completed"
msgstr "オーダーアイテム {} が完了しました"

#: pinakes/main/catalog/services/handle_approval_events.py:106
msgid "Approval Request finished with status '{}'"
msgstr "承認リクエストが '{}' のステータスで終了しました"

#: pinakes/main/catalog/services/handle_approval_events.py:113
msgid "Approval Request finished with status '{}' and reason '{}'"
msgstr "承認リクエストが '{}' のステータスおよび '{}' の理由で終了しました"

#: pinakes/main/catalog/services/sanitize_parameters.py:42
msgid "parameter {} is required and must have a value"
msgstr "パラメーター {} は必須で、値を設定する必要があります"

#: pinakes/main/catalog/services/start_order_item.py:54
msgid "Submitting Order Item {} for provisioning"
msgstr "プロビジョニング用のオーダーアイテム {} の送信"

#: pinakes/main/catalog/services/submit_approval_request.py:57
msgid "Failed to submit request to approval for Order {}, error: {}"
msgstr "オーダー {} の承認リクエストの送信に失敗しました。エラー: {}"

#: pinakes/main/catalog/services/validate_order_item.py:45
msgid ""
"The underlying survey on product {} in the portfolio {} has been changed and "
"is no longer valid, please contact an administrator to fix it."
msgstr ""
"ポートフォリオ {} の製品 {} のベースとなる Survey が変更され、有効ではなくな"
"りました。管理者に連絡して修正してください。"

#: pinakes/main/catalog/views.py:520
msgid "Order {} does not have related order items"
msgstr "オーダー {} には関連するオーダーアイテムがありません"

#: pinakes/main/catalog/views.py:528
msgid "Computed tags for order {}: {}"
msgstr "オーダー {} の計算済みタグ: {}"

#: pinakes/main/inventory/exceptions.py:8
msgid "Refresh already registered"
msgstr "更新はすでに登録されています"

#: pinakes/main/inventory/serializers.py:50
#, python-format
msgid "%(name)s is unavailable, refresh skipped"
msgstr ""

#: pinakes/main/inventory/serializers.py:55
#, python-format
msgid "Refresh failed: %(error)s"
msgstr ""

#: pinakes/main/inventory/serializers.py:59
msgid "adds"
msgstr ""

#: pinakes/main/inventory/serializers.py:60
msgid "deletes"
msgstr ""

#: pinakes/main/inventory/serializers.py:61
msgid "updates"
msgstr ""

#: pinakes/main/inventory/serializers.py:79
#, python-format
msgid "Service Inventories: %(stats)s;\n"
msgstr ""

#: pinakes/main/inventory/serializers.py:84
#, python-format
msgid "Job Templates & Workflows: %(soi_stats)s;\n"
msgstr ""

#: pinakes/main/inventory/serializers.py:89
#, python-format
msgid "Workflow Template Nodes: %(son_stats)s;\n"
msgstr ""

#: pinakes/main/inventory/serializers.py:93
msgid "Nothing to update"
msgstr ""

#: pinakes/main/inventory/serializers.py:116
#, python-format
msgid ""
"Source cannot be changed to url %(new_url)s uuid %(new_install_uuid)s, "
"currently bound to url %(url)s with uuid %(install_uuid)s"
msgstr ""

#: pinakes/main/inventory/serializers.py:122
#, python-format
msgid "Error: %(error)s"
msgstr ""

#: pinakes/main/inventory/services/collect_inventory_tags.py:38
msgid "ServiceOffering object {} not found"
msgstr "サービスオファリングのオブジェクト {} が見つかりません"

#: pinakes/main/inventory/services/get_service_offering.py:34
msgid "Failed to get service offering [{}]"
msgstr "サービスオファリング [{}] の取得に失敗しました"

#: pinakes/main/inventory/task_utils/check_source_availability.py:55
msgid "Check availability completed"
msgstr ""

#: pinakes/main/inventory/task_utils/launch_job.py:69
#, python-format
msgid "Job %(id)s has %(status)s status"
msgstr ""

#: pinakes/main/inventory/views.py:89
msgid "Refresh job {} is already {}, please try again later"
msgstr "ジョブ {} の更新はすでに {} です。後でやり直してください"

#: pinakes/main/models.py:65
msgid "Done"
msgstr ""

#: pinakes/main/models.py:66
msgid "InProgress"
msgstr ""

#: pinakes/main/models.py:67
msgid "Failed"
msgstr ""

#: pinakes/main/models.py:68
msgid "Unknown"
msgstr ""
